name: prometheus-script-exporter
version: '2.15.1'
summary: Prometheus exporter to execute scripts
license: Apache-2.0
contact: luca.bello@canonical.com
issues: https://github.com/canonical/script-exporter-snap/issues
source-code: https://github.com/canonical/script-exporter-snap
website: https://github.com/ricoberger/script_exporter
description: "Script exporter allows to execute scripts and collect metrics through Prometheus from the output or the exit status."
base: core24
grade: stable
confinement: strict
compression: lzo
platforms:
  amd64:
  arm64:
  ppc64el:
  s390x:
plugs:
  etc-script-exporter:
    interface: system-files
    read:
      - /etc/script-exporter.yaml
apps:
  script-exporter:
    daemon: simple
    command: command-wrapper
    install-mode: disable
    restart-condition: on-failure
    plugs:
      - network-bind
      - time-control
      - hardware-observe
      - mount-observe
      - network-observe
      - system-observe
      - log-observe
      - etc-script-exporter
parts:
  wrapper:
    plugin: dump
    source: ./snap/local
    source-type: local
    override-build: |
      cp command-wrapper $CRAFT_PART_INSTALL/
  script-exporter:
    plugin: go
    source: https://github.com/ricoberger/script_exporter
    source-type: git
    source-tag: "v2.15.1"
    build-snaps:
      - go
    build-environment:
      - CGO_ENABLED: 0
    override-build: |
      make build
      cp bin/script_exporter $CRAFT_PART_INSTALL/script_exporter
